language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-jdcproj' ]; then cd .. && eval "mv $currentfolder generator-jdcproj" && cd generator-jdcproj; fi
